version: "3"
services:
  shmarql:
    image: ghcr.io/epoz/shmarql:v0.31
    ports:
      - "9000:8000"
    environment:
      - PREFIXES_FILEPATH=/data/prefixes.json
      - SERVICE_DESCRIPTION_TITLE=Viewsari
      - DEBUG=1
      - SCHPIEL_PATH=/data/www
      - DATA_LOAD_PATHS=/data/
      - DOMAIN=localhost:9000
    volumes:
      - "./data/:/data/"
      - "./data/templates/:/src/templates/"
      - "./data/static/:/src/static/"
