services:
  viewsari:
    build: .
    volumes:
      - ./data:/app/data
      - ./annotations:/app/annotations
    environment:
      - DATA_DIR=/app/data/kg_foundation
      - ANNOTATIONS_DIR=/app/annotations
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - viewsari
    restart: unless-stopped
